# Generated by Django 3.2.5 on 2021-08-02 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5df633c0-a96f-400a-b1a0-70ac78fa80d6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
