# Generated by Django 3.2.5 on 2021-07-30 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210730_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6d4b5c6-cd73-4b5c-bc04-502af6fa05fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
